//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mexify.Web.User {
    
    
    public partial class MintNFT {

        // Messages
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;

        // Stats
        protected global::System.Web.UI.WebControls.Literal litTotalCollections;
        protected global::System.Web.UI.WebControls.Literal litTotalMinted;
        protected global::System.Web.UI.WebControls.Literal litTotalHolders;
        protected global::System.Web.UI.WebControls.Literal litFloorPrice;
        protected global::System.Web.UI.WebControls.Literal litMyNFTCount;

        // Collections
        protected global::System.Web.UI.WebControls.Repeater rptCollections;
        protected global::System.Web.UI.WebControls.Panel pnlNoCollections;

        // Mint form
        protected global::System.Web.UI.WebControls.Panel pnlMintError;
        protected global::System.Web.UI.WebControls.Literal litMintError;
        protected global::System.Web.UI.WebControls.Panel pnlMintSuccess;
        protected global::System.Web.UI.WebControls.Literal litMintSuccess;
        protected global::System.Web.UI.WebControls.DropDownList ddlCollection;
        protected global::System.Web.UI.WebControls.TextBox txtNFTName;
        protected global::System.Web.UI.WebControls.TextBox txtNFTDescription;
        protected global::System.Web.UI.WebControls.TextBox txtQuantity;
        protected global::System.Web.UI.WebControls.TextBox txtRecipientAddress;
        protected global::System.Web.UI.WebControls.Literal litMintPrice;
        protected global::System.Web.UI.WebControls.Literal litQuantity;
        protected global::System.Web.UI.WebControls.Literal litGasFee;
        protected global::System.Web.UI.WebControls.Literal litTotalPrice;
        protected global::System.Web.UI.WebControls.Literal litUserBalance;
        protected global::System.Web.UI.WebControls.Button btnMint;

        // My NFTs
        protected global::System.Web.UI.WebControls.Repeater rptMyNFTs;
        protected global::System.Web.UI.WebControls.Panel pnlNoNFTs;

        // History
        protected global::System.Web.UI.WebControls.Repeater rptHistory;
        protected global::System.Web.UI.WebControls.Panel pnlNoHistory;

        // Hidden fields
        protected global::System.Web.UI.WebControls.HiddenField hfActiveTab;
        protected global::System.Web.UI.WebControls.HiddenField hfMintPrice;
        protected global::System.Web.UI.WebControls.HiddenField hfGasFee;
    }
}
