//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mexify.Web.User {
    
    
    public partial class Mmining {

        // Overview tab
        protected global::System.Web.UI.WebControls.Literal litTotalHashrate;
        protected global::System.Web.UI.WebControls.Literal litDailyEarning;
        protected global::System.Web.UI.WebControls.Literal litActiveRigs;
        protected global::System.Web.UI.WebControls.Literal litTotalEarned;
        protected global::System.Web.UI.WebControls.Literal litTodayEarnings;
        protected global::System.Web.UI.WebControls.Literal litPendingPayout;
        protected global::System.Web.UI.WebControls.Literal litRigCount;

        // My Rigs tab
        protected global::System.Web.UI.WebControls.Repeater rptRigs;
        protected global::System.Web.UI.WebControls.Panel pnlNoRigs;

        // Plans tab
        protected global::System.Web.UI.WebControls.Repeater rptPlans;
        protected global::System.Web.UI.WebControls.Panel pnlNoPlans;

        // History tab
        protected global::System.Web.UI.WebControls.Literal litLifetimeEarnings;
        protected global::System.Web.UI.WebControls.Literal litMonthEarnings;
        protected global::System.Web.UI.WebControls.Literal litTotalPayouts;
        protected global::System.Web.UI.WebControls.Repeater rptEarnings;
        protected global::System.Web.UI.WebControls.Panel pnlNoEarnings;

        protected global::System.Web.UI.WebControls.HiddenField hfActiveTab;
    }
}
