//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mexify.Web.User {
    
    
    public partial class NFTs {

        protected global::System.Web.UI.WebControls.Literal litOwnedCount;
        protected global::System.Web.UI.WebControls.Literal litCreatedCount;
        protected global::System.Web.UI.WebControls.Literal litTotalValue;
        protected global::System.Web.UI.WebControls.Literal litTotalUSD;
        protected global::System.Web.UI.WebControls.Literal litTotalOwned;
        protected global::System.Web.UI.WebControls.Literal litTotalCreated;
        protected global::System.Web.UI.WebControls.Literal litTotalSales;
        protected global::System.Web.UI.WebControls.Literal litRoyalties;
        protected global::System.Web.UI.WebControls.Literal litTotalPurchases;
        protected global::System.Web.UI.WebControls.Literal litTotalSalesActivity;
        protected global::System.Web.UI.WebControls.Literal litMintingFees;
        protected global::System.Web.UI.WebControls.Repeater rptRecentActivity;
        protected global::System.Web.UI.WebControls.Repeater rptFilterCollections;
        protected global::System.Web.UI.WebControls.Repeater rptOwnedNFTs;
        protected global::System.Web.UI.WebControls.Panel pnlNoOwned;
        protected global::System.Web.UI.WebControls.Repeater rptCreatedNFTs;
        protected global::System.Web.UI.WebControls.Panel pnlNoCreated;
        protected global::System.Web.UI.WebControls.Repeater rptAllActivity;
        protected global::System.Web.UI.WebControls.Panel pnlNoActivity;
    }
}
