//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mexify.Web.User {
    
    
    public partial class Transactions {
        protected global::System.Web.UI.WebControls.Literal litTotalVolume;
        protected global::System.Web.UI.WebControls.Literal litTotalVolumeUSD;
        protected global::System.Web.UI.WebControls.Literal litTotalCount;
        protected global::System.Web.UI.WebControls.Literal litSuccessRate;
        protected global::System.Web.UI.WebControls.Literal litTotalInflow;
        protected global::System.Web.UI.WebControls.Literal litTotalOutflow;
        protected global::System.Web.UI.WebControls.Literal litNetBalance;
        protected global::System.Web.UI.WebControls.Literal litPendingCount;
        protected global::System.Web.UI.WebControls.Literal litShowingFrom;
        protected global::System.Web.UI.WebControls.Literal litShowingTo;
        protected global::System.Web.UI.WebControls.Literal litTotalRecords;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlType;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlCurrency;
        protected global::System.Web.UI.WebControls.TextBox txtDateFrom;
        protected global::System.Web.UI.WebControls.TextBox txtDateTo;
        protected global::System.Web.UI.WebControls.Button btnApply;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Button btnExportCSV;

        protected global::System.Web.UI.WebControls.Repeater rptTransactions;
        protected global::System.Web.UI.WebControls.Panel pnlNoTransactions;

        // Deposits tab
        protected global::System.Web.UI.WebControls.Literal litTotalDeposits;
        protected global::System.Web.UI.WebControls.Literal litDepositCount;
        protected global::System.Web.UI.WebControls.Literal litAvgDeposit;
        protected global::System.Web.UI.WebControls.Repeater rptDeposits;
        protected global::System.Web.UI.WebControls.Panel pnlNoDeposits;

        // Withdrawals tab
        protected global::System.Web.UI.WebControls.Literal litTotalWithdrawals;
        protected global::System.Web.UI.WebControls.Literal litWithdrawalCount;
        protected global::System.Web.UI.WebControls.Literal litTotalFees;
        protected global::System.Web.UI.WebControls.Repeater rptWithdrawals;
        protected global::System.Web.UI.WebControls.Panel pnlNoWithdrawals;

        // Earnings tab
        protected global::System.Web.UI.WebControls.Literal litTotalEarnings;
        protected global::System.Web.UI.WebControls.Literal litROIEarnings;
        protected global::System.Web.UI.WebControls.Literal litStakingEarnings;
        protected global::System.Web.UI.WebControls.Literal litReferralEarnings;
        protected global::System.Web.UI.WebControls.Repeater rptEarnings;
        protected global::System.Web.UI.WebControls.Panel pnlNoEarnings;

        // Investments tab
        protected global::System.Web.UI.WebControls.Literal litTotalInvested;
        protected global::System.Web.UI.WebControls.Literal litInvestmentCount;
        protected global::System.Web.UI.WebControls.Repeater rptInvestments;
        protected global::System.Web.UI.WebControls.Panel pnlNoInvestments;

    }
}
